sudo: required

language: generic

notifications:
  email: false

services:
  - docker

before_install:
  - docker pull goofacz/omnetpp-inet-travis:latest

script:
  - docker run -i -t -e PROJECT_NAME=smile-algorithm-ss-twr -v /home/travis/build/$TRAVIS_REPO_SLUG:/root/smile-algorithm-ss-twr goofacz/omnetpp-inet-travis:latest
