//
// Generated file, do not edit! Created by nedtool 5.2 from ResponseFrame.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SMILE__ALGORITHM__SS_TWR_RESPONSEFRAME_M_H
#define __SMILE__ALGORITHM__SS_TWR_RESPONSEFRAME_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include <inet/linklayer/ideal/IdealMacFrame_m.h>  
// }}


namespace smile {
namespace algorithm {
namespace ss_twr {

/**
 * Class generated from <tt>ResponseFrame.msg:25</tt> by nedtool.
 * <pre>
 * packet ResponseFrame extends inet::IdealMacFrame
 * {
 *     unsigned long sequenceNumber = 0;
 * }
 * </pre>
 */
class ResponseFrame : public ::inet::IdealMacFrame
{
  protected:
    unsigned long sequenceNumber;

  private:
    void copy(const ResponseFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ResponseFrame&);

  public:
    ResponseFrame(const char *name=nullptr, short kind=0);
    ResponseFrame(const ResponseFrame& other);
    virtual ~ResponseFrame();
    ResponseFrame& operator=(const ResponseFrame& other);
    virtual ResponseFrame *dup() const override {return new ResponseFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned long getSequenceNumber() const;
    virtual void setSequenceNumber(unsigned long sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ResponseFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ResponseFrame& obj) {obj.parsimUnpack(b);}

} // namespace ss_twr
} // namespace algorithm
} // namespace smile

#endif // ifndef __SMILE__ALGORITHM__SS_TWR_RESPONSEFRAME_M_H

